### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by redips** [GaryClarke/learn-oophp#2]
Hi @GaryClarke and @Iloba I noticed that in almost every lesson (branch) there aren't the `composer.json`, or if is present it's called just `json` and the `App` namespace is wrongly defined as it should include the "Chapter X" folder.  
You can check in branches 58, 59, 60 just as example, but as I said it's the same for all the chapters/branches.

**Comment by GaryClarke** [comment]
OK, I'll look into it. Can you show me where you saw the files just called json?

**Comment by GaryClarke** [comment]
I've now corrected the names of all the composer.json files. The files were copied directly from the lessons and that is why there isn't one attached to branch...sorry that's not great but this repo was created retrospectively.

All my current courses include a repo which is created in conjunction with the course as it's created.

The namespaces are actually correct as each chapter is its own individual project with its own composer.json where the namespace is defined.  

Thanks @redips for pointing this stuff out.
